name: "📚 Hashnode Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📥  blog-left"
        uses: "HohShenYien/action-hashnode-blog@1745d9cd48b47b207fca870c39a8c1957dcb3179"
        with:
          USERNAME: 'ShenYien'
          BLOG_URL: 'https://blogs.shenyien.cyou'
          COUNT: 4
          FILE: "README.md"
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
