name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.21
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: HohShenYien
          template: classic
          base: header, activity, community
          config_timezone: Asia/Kuala Lumpur
          filename: res/github-metrics.svg
          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: res/habits-metrics.svg
          config_timezone: Asia/Kuala Lumpur
          template: classic
          base: ""
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 6
          plugin_habits_languages_threshold: 0%
      
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: res/language-metrics.svg
          template: classic
          base: ""
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: html
